### PR TITLE
Flask app

### PR DESCRIPTION
**Pull request by krsnik93**
Main changes in this PR include:

- Flask app returning results from the database
- proper coverage calculation for participants
- introduction of `includeInTimeline` flag
- cache busting
- ...

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks for this @krsnik93 

As we get ready to deploy the dashboard to the analyst network I can just think of this one issue:

* the start/end date is hard-coded in the code, in order to retrieve the limited test data we have setup for serials
* but, on the analyst network is should default to "Yesterday".

So, I think we need a toggle checkbox for switching between the test date & yesterday.

**Comment by IanMayo** [comment]
Hello @krsnik93 - are you aware of any other work that is required on this before we merge?

(I'm happy to fix the start-date issue after it's merged - that can be a much smaller PR).

**Comment by krsnik93** [comment]
@IanMayo not sure it needs to be merged before, but this branch does not have the `masonry` work by @tanganellilore. I see that the [PR](https://github.com/debrief/pepys-timeline/pull/15) was closed but I would need to add this by hand. I am also not sure whether we agreed to include that work in the end or not.

**Comment by krsnik93** [comment]
I would still advise to merge this first and then add `masonry` stuff if it needs to be added

**Comment by robintw** [comment]
@krsnik93 Is the `/timelines` route still being used? It seems to provide test data of some sort - is that a hangover from testing that was done before we actually connected to the database? If so, could you remove it.

**Comment by krsnik93** [comment]
@robintw you are completely right. Removed now.

**Review by IanMayo — APPROVED** [review]
nice piece of work, thanks.

**Pull request merged**
