### PR TITLE
[WIP] UI Prototyping

### PR DESCRIPTION
**Pull request by krsnik93**
Fixes issue [#2](https://github.com/debrief/pepys-timeline/issues/2).

### CODE REVIEW

**Comment by IanMayo** [comment]
Ooh, Heroku failed. It looks like we need to provide a particular file to give Heroku a clue about what type of app this is.

**Comment by IanMayo** [comment]
Hello @krsnik93  - I've had a play. I've persuaded Heroku that it's a PHP app - so now we get review copies at Heroku:
image

I've also pulled in the missing dependencies - so that app now works.

**Comment by krsnik93** [comment]
Cheers, I was debating internally whether to have the visavail repo as a submodule of this repo. Your solution works great as well.

**Comment by krsnik93** [comment]
I was not aware that you will be hosting the app on Heroku, AWS setup might be redundant in that case.

**Comment by IanMayo** [comment]
Don't worry @krsnik93  - it's just for this early prototyping.  It's quick & easy to get it to host some static html/js.

I don't think it will sort out Python hosting issue.

Aah, hold on - maybe it will solve the Python issue :-)
https://devcenter.heroku.com/articles/getting-started-with-python

**Comment by IanMayo** [comment]
That's good:

image

**Comment by krsnik93** [comment]
Please disregard the stock html button, I think a lightweight css framework would be a good fit for this task. Perhaps bulma: https://github.com/jgthms/bulma

EDIT: bootstrap is a great candidate as well seeing as everyone is familiar with it

**Comment by IanMayo** [comment]
Great - thanks.
If you have time available, can I suggest some steps to move it closer to our mockup?
* [ ] Only let chart use 20% of the width - since we'll be displaying up to 5
* [x] Compress vertical height (remove vertical whitespace) - since we may display up to 25 ships in a column

**Comment by krsnik93** [comment]
No problem, I am trying to add icons next to the names and will then move on to those two.

**Comment by krsnik93** [comment]
I am seeing really poor results when trying to squeeze in 5 charts into same row. Results for 4 charts seem more reasonable. Might be just my screen though. Could you check `index.html` to see how it looks for you? Would you insist on at least 5 charts in one row?

5 in a row:
image

4 in a row:
image

**Comment by IanMayo** [comment]
That's surprising :-)

That's the benefit of us doing this early experimenting. There is a lot of horizontal whitespace. Maybe that can be reduced.

**Comment by IanMayo** [comment]
Hello @krsnik93  - I've done some googling, and some playing with the widths. I've got 5 graphs showing.

I didn't realise how extensive the SVG was.  It may be more challenging than I expected to modify the layout.

image

**Comment by krsnik93** [comment]
Looks good but keep in mind that with the latest changes the page is not responsive anymore. I am not sure how important it is that the page looks good on smaller screen sizes as well.

**Comment by IanMayo** [comment]
> responsive
That's not an issue right now. The only perceived use is on a 65-inch, 3400 pixel wall-mounted display.

Note: have also experimented with removing the "measure" labels. Yes, they're needed to know which platform the line is for, but _hopefully_ we can move the label to onto the bar, like in the mockup.

I guess that to achieve our mockup layout we're going to have to either:
* do some d3/SVG fiddling once the charts have rendered
* use a modified version of `visavail`
* override some visavail functions with our own custom ones.

But - right now I'm happy to defer the above until long into the future.  I've marked some of the requirements with **Defer** where it seems there isn't sufficient cost/benefit to do the d3 fiddling right now.

**Comment by robintw** [comment]
@krsnik93 I had a very brief look to see if I could reduce the padding between the platform names and the graphs - and therefore make more space for the graphs. Have you tried playing with the visavail left margin option? I see it's still set to 100 in the code - does reducing that remove some of the padding?

**Comment by IanMayo** [comment]
I tried that @robintw .  I reduced the left margin to 50, and it clipped the text and just left the 50px whitespace 🤣

**Comment by krsnik93** [comment]
@IanMayo I managed to put ship names inside of bars. Will be looking to resize the timelines to fill the space after hiding the labels on the left. Same principle can be used for remaining tasks.

**Comment by IanMayo** [comment]
Well done @krsnik93 

But, if it's achievable, I think the most robust route would be to get visavail modified to include options to support the layout we're looking for.  The dom-fiddling is a last resort, to be honest.

As mentioned in Slack, I'd like to close this PR shortly, and let you work on the `flask` bits in a new branch. Then I can get someone working on the `visavail` bits in a fork from `main`.

**Review by IanMayo — APPROVED** [review]
I'm accepting this early, so that we have a (relatively) firm base to start the separate `flask` & `visavail` modifications.

**Pull request merged**
