### PR TITLE
Feature/pepys import 840 - SQL to get timeline data

### PR DESCRIPTION
**Pull request by rnllv**
Dashboard metadata and stats procedures for https://github.com/debrief/pepys-import/issues/840

### CODE REVIEW

**Comment by rnllv** [comment]
The functions are now available in tracstor_trial1 database. Here are sample invocations of the same.

### To invoke the **Dashboard Metadata** function
```SQL
select * from pepys.dashboard_metadata('2021-01-05','2021-01-05');  --Argument 1: Serial Start date, Argument 2: Serial End date
```
#### Result
record_type|serial_id|platform_id|name|platform_type_name|start|end|gap_seconds
-|-|-|-|-|-|-|-
SERIALS|54f6d015-8adf-47f4-bf02-33e06fbe0725||J05050||2021-01-05 09:00:00|2021-01-05 11:00:00|
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|42c64091-4210-4cb1-a8cc-77a161ce8dc8|FORE|Warship|2021-01-05 09:00:00|2021-01-05 11:00:00|30
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|0d88a709-98c9-42b4-a942-1af95306fc6a|GRNN|Warship|2021-01-05 09:00:00|2021-01-05 11:00:00|30
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|c35ead47-587a-4a1d-9d56-c6df004b2869|SALT|Warship|2021-01-05 10:00:00|2021-01-05 11:00:00|30
PARTICIPANTS||42c64091-4210-4cb1-a8cc-77a161ce8dc8|FORE|Warship|||
PARTICIPANTS||0d88a709-98c9-42b4-a942-1af95306fc6a|GRNN|Warship|||
PARTICIPANTS||c35ead47-587a-4a1d-9d56-c6df004b2869|SALT|Warship|||


### To invoke the **Dashboard Stats** function
```SQL
select * from pepys.dashboard_stats('
[
   {   "serial_id": "faa18ef7-6823-33dc-0f16-de6e4b2c02f3",
       "platform_id": "50d64387-9f91-4c6f-8933-f4e7b1a7d8ab",
       "start": "2020-11-15 00:00:00",
       "end": "2020-11-15 23:59:59",
       "gap_seconds": 30
   }
]',
'["G","C"]');
```
#### Result
resp_range_type|resp_start_time|resp_end_time|resp_platform_id
-|-|-|-
C|2020-11-15 00:00:00|2020-11-15 01:22:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 01:22:01|2020-11-15 01:28:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 01:28:01|2020-11-15 01:36:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 01:36:01|2020-11-15 01:39:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 01:39:01|2020-11-15 01:45:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 01:45:01|2020-11-15 01:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 01:49:01|2020-11-15 01:50:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 01:50:01|2020-11-15 02:05:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 02:05:01|2020-11-15 06:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 06:49:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 07:00:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
G|2020-11-15 07:00:01|2020-11-15 07:10:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab
C|2020-11-15 07:10:01|2020-11-15 23:59:59|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab

**Comment by IanMayo** [comment]
@arunlal-v  - if the time is missing, doesn't the database presume midnight?  If that's the case that start-date/end-date should cover zero time period, right?

**Comment by rnllv** [comment]
> @arunlal-v - if the time is missing, doesn't the database presume midnight? If that's the case that start-date/end-date should cover zero time period, right?

I've handled that part in the function. Only the date portion of the timestamps are compared.

```SQL
	where 
		s.start::date = to_date(ui_inp_start_date, 'YYYY-MM-DD')
			and
		s.end::date = to_date(ui_inp_end_date, 'YYYY-MM-DD')
```

**Comment by IanMayo** [comment]
I think the phase 2 call should omit the platform. We wish to see the coverages for all platforms for this serial.  Aah, we would need to provide the gap interval for each platform.  So, we'd provide an array of platform-id and gap intervals.

We'd group the results by `resp_platform_id`.

**Comment by rnllv** [comment]
Yes. The results are sorted based on platform_id, start_time, and end_time

```SQL
order by
	platform_id asc,
	start_time asc,
	end_time asc;

```

**Comment by IanMayo** [comment]
Thanks. But, it appears that we're just requesting details for a single platform/interval.  That could be 30? calls.  If we do it once per serial then it's maximum of 5.

**Comment by rnllv** [comment]
> Thanks. But, it appears that we're just requesting details for a single platform/interval. That could be 30? calls. If we do it once per serial then it's maximum of 5.

The input is an array of objects. Here's another example which queries for 2 different platforms in the same serial.
```SQL
select * from pepys.dashboard_stats('
[
   {   "serial_id": "faa18ef7-6823-33dc-0f16-de6e4b2c02f3",
       "platform_id": "50d64387-9f91-4c6f-8933-f4e7b1a7d8ab",
       "start": "2020-11-15 00:00:00",
       "end": "2020-11-15 23:59:59",
       "gap_seconds": 30
   },
   {   "serial_id": "faa18ef7-6823-33dc-0f16-de6e4b2c02f3",
       "platform_id": "de324387-9f91-4c6f-8933-f4e7b1a7d8ab",
       "start": "2020-11-15 00:00:00",
       "end": "2020-11-15 23:59:59",
       "gap_seconds": 60
   }
]',
'["G","C"]');
```

**Comment by IanMayo** [comment]
Ok, that's fine.

**Comment by IanMayo** [comment]
Aah, ok.  So, can the `dashboard_stats` be called for multiple serials at once?  Or just one serial (multiple serials would be more responsive).

One other thing. We need the `serial_number` and `exercise` fields for each serial. They're used in the display.

One last thing. The `PARTICIPANTS` rows in the results for phase 1 don't seem of value. The data is all present in `SERIAL_PARTICIPANTS`.

**Comment by rnllv** [comment]
>Aah, ok.  So, can the `dashboard_stats` be called for multiple serials at once?  Or just one serial (multiple serials would be more responsive).

The query can handle multiple serials at once. Let's test it and check for performance lags, if any. And yes, one call per serial would also work, with each call returning quickly.

>One other thing. We need the `serial_number` and `exercise` fields for each serial. They're used in the display.

Sure, I'll update the **Dashboard Metadata** query

>One last thing. The `PARTICIPANTS` rows in the results for phase 1 don't seem of value. The data is all present in `SERIAL_PARTICIPANTS`.

I'll remove them.

**Comment by rnllv** [comment]
Changes are committed and pushed to branch. Merge is pending.

**Comment by rnllv** [comment]
### To invoke the **Dashboard Metadata** function
Here, **name** is the serial_number, and was previously present. **exercise** is the only new column added.
```SQL
select * from pepys.dashboard_metadata('2021-01-05','2021-01-05');  --Argument 1: Serial Start date, Argument 2: Serial End date
```
#### Result
record_type|serial_id|platform_id|name|exercise|platform_type_name|start|end|gap_seconds
-|-|-|-|-|-|-|-|-
SERIALS|54f6d015-8adf-47f4-bf02-33e06fbe0725||J05050|CASEX 4A||2021-01-05 09:00:00|2021-01-05 11:00:00|
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|42c64091-4210-4cb1-a8cc-77a161ce8dc8|FORE||Warship|2021-01-05 09:00:00|2021-01-05 11:00:00|30
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|0d88a709-98c9-42b4-a942-1af95306fc6a|GRNN||Warship|2021-01-05 09:00:00|2021-01-05 11:00:00|30
SERIAL PARTICIPANT|54f6d015-8adf-47f4-bf02-33e06fbe0725|c35ead47-587a-4a1d-9d56-c6df004b2869|SALT||Warship|2021-01-05 10:00:00|2021-01-05 11:00:00|30

**Comment by rnllv** [comment]
> Aah, ok. So, can the `dashboard_stats` be called for multiple serials at once? Or just one serial (multiple serials would be more responsive).

@IanMayo, forgot to mention one thing. We had removed **serial_id** from the query result as you mentioned that it'll be queried once per serial. So, this version of the query has to be called once per serial.

But, if you want to try calling multiple serials at once, we can put the **serial_id** back in the response and give it a try.

**Comment by IanMayo** [comment]
We can navigate from serial participant back to serial, can't we?

**Comment by rnllv** [comment]
We could identify the **serial_id** based on the **start_time** and **end_time**, but that will entail additional calculations at the front end.

**Comment by IanMayo** [comment]
> We could identify the *serial_id* based on the *start_time* and *end_time*,
> but that will entail additional calculations at the front end.

Aah, then let's have the serial number ('J07110') in the phase 2 output.

**Comment by rnllv** [comment]
The stats query is updated to return **serial_id** as well. Below is the updated result-set format. 

The query invocation remains same, but the **gap_seconds** field should now send the *weighted* gap (multiplied by factor 5) instead of just the gap defined in **pepys."PlatformTypes"** table. Changes are committed and pushed to branch, and deployed to tracstor_trial1 db.


#### Result
resp_range_type|resp_start_time|resp_end_time|resp_platform_id|resp_serial_id
-|-|-|-|-
C|2020-11-15 00:00:00|2020-11-15 01:22:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 01:22:01|2020-11-15 01:28:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 01:28:01|2020-11-15 01:36:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 01:36:01|2020-11-15 01:39:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 01:39:01|2020-11-15 01:45:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 01:45:01|2020-11-15 01:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 01:49:01|2020-11-15 01:50:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 01:50:01|2020-11-15 02:05:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 02:05:01|2020-11-15 06:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 06:49:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 07:00:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
G|2020-11-15 07:00:01|2020-11-15 07:10:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3
C|2020-11-15 07:10:01|2020-11-15 23:59:59|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|faa18ef7-6823-33dc-0f16-de6e4b2c02f3

**Comment by IanMayo** [comment]
serial_id - there is a humans readable field called serial_number. This works consume less bandwidth.

**Comment by rnllv** [comment]
That information is already sent as part of the **dashboard_metadata** result. Once the **dashboard_stats** results are in, they have to be *merged* using the **serial_id** field with the dashboard diagrams. **serial_number** or **exercise** cannot be used as they are not guaranteed to be unique.

I can add **serial_number** and/or **exercise** fields as part of the **dashboard_stats** results as well, but they shouldn't be used to *merge* the phase 1 and 2 results. Let me know if I've to include these 2 fields.

**Comment by IanMayo** [comment]
in this context, the humans in the loop guarantee serial number to be unique for that wargame. It's they weren't unique, some ships would have to be in two places at once.

**Comment by rnllv** [comment]
Ok, so shall I replace **serial_id** with **serial_number**?

If bandwidth is the concern, then [aliases for platform_id and serial_id](https://github.com/debrief/pepys-import/issues/840#issuecomment-823343921) will be far more efficient and stable.

**Comment by IanMayo** [comment]
Yes, let's move to serial_number, please.

> aliases for platform & serial would be more efficient

Yes, but they would introduce another level of complexity that isn't currently justified. Let's not.

**Comment by rnllv** [comment]
**serial_id** is replaced with **serial_number** in the **dashboard_stats** query. Here's the updated result set. Query invocation remains same.

#### Result
resp_range_type|resp_start_time|resp_end_time|resp_platform_id|resp_serial_id
-|-|-|-|-
C|2020-11-15 00:00:00|2020-11-15 01:22:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 01:22:01|2020-11-15 01:28:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 01:28:01|2020-11-15 01:36:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 01:36:01|2020-11-15 01:39:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 01:39:01|2020-11-15 01:45:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 01:45:01|2020-11-15 01:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 01:49:01|2020-11-15 01:50:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 01:50:01|2020-11-15 02:05:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 02:05:01|2020-11-15 06:49:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 06:49:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 07:00:01|2020-11-15 07:00:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
G|2020-11-15 07:00:01|2020-11-15 07:10:01|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050
C|2020-11-15 07:10:01|2020-11-15 23:59:59|50d64387-9f91-4c6f-8933-f4e7b1a7d8ab|J05050

**Comment by rnllv** [comment]
The latest commit in this pull should resolve [this issues](https://github.com/debrief/pepys-timeline/issues/10) as well.

**Comment by rnllv** [comment]
The latest version of the **dashboard_metadata** is now deployed to tracstor_trial1 database.

**Comment by krsnik93** [comment]
@arunlal-v  I am getting:
`
curs.execute(SERIALS_QUERY)
psycopg2.errors.UndefinedColumn: column "ui_inp_end_date" does not exist
LINE 14:         s.start::date <= to_date(ui_inp_end_date, 'YYYY-MM-D...
`
when running `dashboard_metadata.sql` and:
`curs.execute(SERIALS_QUERY)
psycopg2.errors.UndefinedColumn: column "ui_inp_ser_plat_json" does not exist
LINE 5:         ui_inp_ser_plat_json::json spij,
`
when running `dashboard_stats.sql`

EDIT: @IanMayo for params from Slack

**Comment by rnllv** [comment]
> @arunlal-v I am getting:
> `curs.execute(SERIALS_QUERY) psycopg2.errors.UndefinedColumn: column "ui_inp_end_date" does not exist LINE 14: s.start::date <= to_date(ui_inp_end_date, 'YYYY-MM-D...`
> when running `dashboard_metadata.sql` and:
> `curs.execute(SERIALS_QUERY) psycopg2.errors.UndefinedColumn: column "ui_inp_ser_plat_json" does not exist LINE 5: ui_inp_ser_plat_json::json spij, `
> when running `dashboard_stats.sql`
> 
> EDIT: @IanMayo for params from Slack

Looks like the parameters are missing. This should help.
https://github.com/debrief/pepys-timeline/pull/8#issuecomment-823399947

**Comment by krsnik93** [comment]
@arunlal-v please correct me if I am wrong, but the second query (`dashboard_stats.sql`) returns consolidated coverage/gap periods for serials. I think we need this data per participant as well (to be able to display a separate timeline for each serial participant). @IanMayo will be able to confirm.

**Comment by rnllv** [comment]
> @arunlal-v please correct me if I am wrong, but the second query (`dashboard_stats.sql`) returns consolidated coverage/gap periods for serials. I think we need this data per participant as well (to be able to display a separate timeline for each serial participant). @IanMayo will be able to confirm.

It's not consolidated coverage/gap periods, @krsnik93. It's for individual participants.

**Comment by rnllv** [comment]
To be specific, it's for each participant per serial.

**Comment by krsnik93** [comment]
@arunlal-v great, could we just add the serial participant id into the response? Right now it's hard to differentiate them in the response.

**Comment by krsnik93** [comment]
`platform_id` and `serial_id` are in, but having `serial_participant_id` as well would be of great help.

**Comment by krsnik93** [comment]
@arunlal-v or is `platform_id` used for this purpose?

**Comment by rnllv** [comment]
> @arunlal-v or is `platform_id` used for this purpose?

It's the combination of serial_id and platform_id. It's sorted as below.

https://github.com/debrief/pepys-timeline/pull/8#issuecomment-823416093

**Comment by krsnik93** [comment]
Thank you, sorry for the confusion.

**Comment by rnllv** [comment]
No problem.

**Comment by krsnik93** [comment]
@arunlal-v just spotted something else, I think for `dashboard_metadata.sql`, you are returning the actual `serial_id`, but for `dashboard_stats.sql`, `resp_serial_id` is just the name of the serial (for example, `J05050` instead of `54f6d015-8adf-47f4-bf02-33e06fbe0725`).

**Comment by krsnik93** [comment]
I can work around that one though.

**Comment by rnllv** [comment]
> @arunlal-v just spotted something else, I think for `dashboard_metadata.sql`, you are returning the actual `serial_id`, but for `dashboard_stats.sql`, `resp_serial_id` is just the name of the serial (for example, `J05050` instead of `54f6d015-8adf-47f4-bf02-33e06fbe0725`).

Yep, I too preferred the actual serial id for mapping. But it was changed to serial_number. Sorry, I missed to update the column heading.

https://github.com/debrief/pepys-timeline/pull/8#issuecomment-824269073

**Comment by rnllv** [comment]
> Yes. The results are sorted based on platform_id, start_time, and end_time
> 
> ```sql
> order by
> 	platform_id asc,
> 	start_time asc,
> 	end_time asc;
> ```

This is the updated sort order.

```SQL
order by
	cs.serial_id asc,
	cs.platform_id asc,
	cs.start_time asc,
	cs.end_time asc;
```

**Comment by IanMayo** [comment]
Hmm, @arunlal-v - since platform_id is unique, the start & end times won't be used, will they?

Aah, are you allowing for a platform to appear more than once in a serial?

The analysts would be able to navigate the timelines better if the data was sorted by platform quadgraph than platform id.  
If they're looking for `Wanda` they'll intuitively know to look near the bottom of the column.

**Comment by rnllv** [comment]
>Aah, are you allowing for a platform to appear more than once in a serial?

Yep.

>The analysts would be able to navigate the timelines better if the data was sorted by platform quadgraph than platform id.
>If they're looking for Wanda they'll intuitively know to look near the bottom of the column.

I don't think this should be an issue. The "blank" or "empty" dashboards with platform names and icons are drawn based on the dashboard_metadata query. The coverage is populated based on the phase 2 query (the ```order by``` clause of which we are discussing)

**Review by IanMayo — APPROVED** [review]

**Pull request merged**
